services:
  - type: web
    name: urban-referral-network
    runtime: docker
    rootDir: ./geospatial
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Render
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ConnectionStrings__DefaultConnection
        value: Server=sql8011.arnaco.com;Database=db_a28254_urbaweb;User Id=db_a28254_urbaweb_admin;Password=6Th38P623hLg;Encrypt=true;TrustServerCertificate=true;MultipleActiveResultSets=true
    healthCheckPath: /health